Repository litmuschaos/charthub.litmuschaos.io, pull requests merged in 2019-10, with the labels that each got.

#20 (fix): Add installation steps start the charhub server
  README.md
Labels: Hacktoberfest

#32 fixed Dockerfile.server, added docker-compose.yml
  Dockerfile.server
  README.md
  docker-compose.yml
Labels: Hacktoberfest

#52 (bug): Fix the api url generated by server
  server/routes.go
  src/components/ChartDetails.js
Labels: bug

#54 (fix) : changed "%" to PERCENTAGE
  server/charts/generic/experiments.yaml
  server/charts/generic/pod-network-loss/experiment.yaml
Labels: bug

#60 [staging to master]
  server/charts/generic/generic.chartserviceversion.yaml
Labels: production

#38 Update Installation and Usage instructions in README.md
  README.md
Labels: Hacktoberfest
