Repository litmuschaos/charthub.litmuschaos.io, pull requests merged in 2020-01, with the labels that each got.

#94 (feat)Analytics: Support for cumulative experiment count
  server/pkg/analytics/analytics.go
  src/components/ChartDetails.js
  src/pages/Chart.js
  src/pages/Experiments.js
  src/styles/components/chart-card.scss
  src/styles/components/chart-details.scss
Labels: staging

#95 [cherry-pick to master]
  server/controller/handler/handlers.go
  server/main.go
  server/pkg/analytics/analytics.go
  server/routes/routes.go
  src/components/ChartCard.js
  src/components/ChartDetails.js
  src/components/HomeHeader.js
  src/pages/Chart.js
  src/pages/Experiments.js
  src/pages/Home.js
  src/redux/actionTypes.js
  src/redux/actions.js
  src/redux/reducers/charts.js
  src/styles/components/chart-card.scss
  src/styles/components/chart-details.scss
Labels: production

#98 (Bug):Removed typo from charts.js file
  src/pages/Chart.js
Labels: bug

#97 Bug-Fix:Back- Button Fix
  src/pages/Experiments.js
Labels: bug

#96 (feat)Analytics: Support for cumulative metrics and Footer in hub
  package.json
  public/icons/mayadata-white-logo.png
  server/pkg/analytics/analytics.go
  src/components/ChartCard.js
  src/components/ChartDetails.js
  src/components/Footer.js
  src/components/HomeHeader.js
  src/index.scss
  src/pages/Chart.js
  src/pages/Experiments.js
  src/pages/Home.js
  src/styles/components/chart-card.scss
  src/styles/components/footer.scss
  src/styles/components/home-header.scss
  src/styles/home.scss
  yarn.lock
Labels: enhancement

#107 (feat)charthub: support for video-embedding
  package.json
  public/icons/play-square.png
  server/main.go
  server/pkg/analytics/analytics.go
  src/components/ChartDetails.js
  src/components/VideoModalContent.js
  src/pages/Experiments.js
  src/styles/components/chart-details.scss
  src/styles/components/home-header.scss
  src/styles/components/video-modal-component.scss
Labels: staging
